# .github/release.yml

changelog:
  categories:
    - title: OpenTelemetry & LGTM
      labels:
        - docker-dependency
    - title: Other Changes
      labels:
        - "*"
      exclude:
        authors:
          - dependabot[bot]
          - grafanarenovatebot[bot]
          - renovate-sh-app[bot]
          - renovatebot[bot]
