# OATS is an acceptance testing framework for OpenTelemetry
# https://github.com/grafana/oats/tree/main/yaml
services:
  # Override the OATS-provided lgtm service to enable OBI
  lgtm:
    environment:
      ENABLE_OBI: "true"
      ENABLE_LOGS_OBI: "true"
      # OBI defaults to 60s, which needlessly delays the test's metric assertion.
      OTEL_EBPF_METRICS_INTERVAL: "1s"
    privileged: true
    pid: "host"
    stop_grace_period: 1s

  generate-traffic:
    build:
      context: ../../examples/obi
      dockerfile: generate-traffic.Dockerfile
    depends_on:
      - java
      - python
      - dotnet
      - go
      - nodejs
    stop_grace_period: 1s

  dotnet:
    build:
      context: ../../examples/obi/dotnet
    depends_on:
      - lgtm
    stop_grace_period: 1s

  go:
    build:
      context: ../../examples/obi/go
    depends_on:
      - lgtm
    stop_grace_period: 1s

  java:
    build:
      context: ../../examples/java
      dockerfile: ../obi/java.Dockerfile
    depends_on:
      - lgtm
    stop_grace_period: 1s

  nodejs:
    build:
      context: ../../examples/obi/nodejs
    depends_on:
      - lgtm
    stop_grace_period: 1s

  python:
    build:
      context: ../../examples/python
      dockerfile: ../obi/python.Dockerfile
    depends_on:
      - lgtm
    stop_grace_period: 1s
