[meta]
version = 2

[[suite]]
cases = ["examples/nodejs/oats.yaml"]

[[suite]]
cases = ["examples/python/oats.yaml"]

[[suite]]
cases = ["examples/obi/oats.yaml"]

[[suite]]
cases = ["examples/ebpf-profiler/oats.yaml"]
