apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://localhost:9090

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200

  - name: Loki
    type: loki
    uid: loki
    url: http://localhost:3100

  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://localhost:9090
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        mappedTags: [{ key: 'service.name', value: 'job' }]
        mapTagNamesEnabled: true
        filterByTraceID: true
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'

  - name: Loki
    type: loki
    uid: loki
    url: http://localhost:3100
    jsonData:
      derivedFields:
        - name: 'trace_id'
          matcherRegex: '"traceid":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'
