{
 "title": "RED Metrics (native histogram)",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# RED Metrics: (r)equest rate, (e)rror rate, (d)uration\n\nThis dashboard uses exponential histograms and the stable [OpenTelemetry metrics semantic conventions](https://opentelemetry.io/docs/specs/semconv/general/metrics/).\nTo enable this for the [OpenTelemetry Java instrumentation agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/), set the following environment variables:\n\n```\nexport OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=base2_exponential_bucket_histogram\nexport OTEL_SEMCONV_STABILITY_OPT_IN=http\n```"
   }
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(histogram_count(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(histogram_count(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[5m]))) / sum(histogram_count(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\"}[5m])))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}