service:
  pipelines:
    traces:
      exporters: [otlphttp/traces, otlphttp/external]
    metrics:
      exporters: [otlphttp/metrics, otlphttp/external]
    logs:
      exporters: [otlphttp/logs, otlphttp/external]

exporters:
  otlphttp/external:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
