services:
  lgtm:
    image: grafana/otel-lgtm@sha256:6e14b923e0130b8b294ca5bcc7c94d54e899d150817e6c3ed82d9b665afe5499
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /otel-lgtm/grafana/conf/provisioning/dashboards/custom/custom-dashboard.json
    volumes:
      - ./custom-dashboard.json:/otel-lgtm/grafana/conf/provisioning/dashboards/custom/custom-dashboard.json:ro
      - ./dashboards-provisioning.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml:ro
    networks:
      - java-demo

  java:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: "rolldice"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
    ports:
      - "8080:8080"
    networks:
      - java-demo
    depends_on:
      - lgtm

networks:
  java-demo:
    driver: bridge
