---
name: Acceptance Tests

on: [pull_request]

permissions: {}

jobs:
  acceptance-tests:
    permissions: {}
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: v2026.6.5
          sha256: 9ca3e4e25c26c64886d036fe9ddb2e5415a204f2d5b9c35bf67abd4f15f0f768

      - name: Run acceptance tests
        run: mise run acceptance-tests ${{ github.event.pull_request.head.sha }}
