---
name: Acceptance Tests

on: [pull_request]

permissions: {}

jobs:
  acceptance-tests:
    permissions: {}
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          version: v2026.3.3
          sha256: ed251b4588512ab64e2372fd3dacffd6bad574ae9e20c311fb864ff65c2a6c8a

      - name: Run acceptance tests
        run: mise run acceptance-tests ${{ github.event.pull_request.head.sha }}
