---
name: CI

on:
  pull_request:

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
          fetch-depth: 0 # needed for merge-base used in lint:links-in-modified-files

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: v2026.6.11
          sha256: 4c1036af15efea3a4d83f13481132ec7d7dda15e7ec5869dd70a64072bf1a6c9

      - name: CI checks
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        run: mise run ci
