---
name: Container Scan

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm
  TRIVY_IMAGE_REF: "grafana/otel-lgtm:latest"
  TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
  TRIVY_SEVERITIES: "CRITICAL,HIGH"

jobs:
  scan-image:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: github.event.repository.fork == false

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    permissions:
      security-events: write

    steps:
      - name: Run Trivy (SARIF)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: ${{ env.TRIVY_IMAGE_REF }}
          format: "sarif"
          ignore-unfixed: true
          limit-severities-for-sarif: true
          output: "trivy.sarif"
          severity: ${{ env.TRIVY_SEVERITIES }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # v4.33.0
        if: ${{ !cancelled() }}
        with:
          sarif_file: "trivy.sarif"

      - name: Run Trivy (JSON)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: ${{ env.TRIVY_IMAGE_REF }}
          format: "json"
          ignore-unfixed: true
          output: "trivy.json"
          severity: ${{ env.TRIVY_SEVERITIES }}

      - name: Check for vulnerabilities
        shell: pwsh
        run: |
          $report = Get-Content ./trivy.json | Out-String | ConvertFrom-Json

          $vulnerabilities = @()

          foreach ($target in $report.Results) {
            foreach ($vulnerability in $target.Vulnerabilities) {
              $vulnerabilities += $vulnerability
            }
          }

          $report = @(
            "# Container Image Vulnerability Report",
            ""
          )

          if ($vulnerabilities.Length -eq 0) {
            $report += ":closed_lock_with_key: No vulnerabilities found."
          } else {
            $report += "| Library | Vulnerability | Severity | Status | Installed Version | Fixed Version | Title |"
            $report += "|:--------|:--------------|:---------|:-------|:------------------|:--------------|:------|"

            foreach ($vulnerability in $vulnerabilities) {
              $title = $vulnerability.Title
              if ([string]::IsNullOrEmpty($title)) {
                $title = $vulnerability.Description
              }

              $fixedVersion = $vulnerability.FixedVersion
              if ([string]::IsNullOrEmpty($fixedVersion)) {
                $fixedVersion = "N/A"
              }

              $report +=
                "| $($vulnerability.PkgName) " +
                "| $($vulnerability.VulnerabilityID) " +
                "| $($vulnerability.Severity) " +
                "| $($vulnerability.Status) " +
                "| $($vulnerability.InstalledVersion) " +
                "| ${fixedVersion} " +
                "| [${title}]($($vulnerability.PrimaryURL)) |"
            }
          }

          $report += ""
          $report += ""

          ($report -Join "`n") >> ${env:GITHUB_STEP_SUMMARY}
