---
name: Container Image Build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

permissions: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # renovate: datasource=github-releases depName=cosign packageName=sigstore/cosign
  COSIGN_VERSION: v3.0.6

jobs:
  build:
    runs-on: ubuntu-24.04

    concurrency:
      group: "${{ github.workflow }}-${{ github.sha }}"
      cancel-in-progress: false

    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get Git commit timestamp
        shell: bash
        run: echo "GIT_COMMIT_EPOCH=$(git log -1 --pretty=%ct)" >> "${GITHUB_ENV}"

      - name: Build and push GHCR image
        id: push
        uses: grafana/shared-workflows/actions/docker-build-push-image@34f27887c37cafe70d34af57dfc86b468a31b8c4 # docker-build-push-image/v0.3.3
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
          SOURCE_DATE_EPOCH: ${{ env.GIT_COMMIT_EPOCH }}
        with:
          context: docker
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          registries: ghcr
          image-name: ${{ env.IMAGE_NAME }}
          build-args: |
            LGTM_VERSION=${{ github.ref_name }}
          tags: |-
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |-
            org.opencontainers.image.ref.name=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            vcs-ref=${{ github.sha }}
            version=${{ github.ref_name }}

      - name: Generate artifact attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          push-to-registry: true
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Sign container images
        if: github.event_name != 'pull_request'
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
          TAGS: ${{ steps.push.outputs.tags }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes "{}@${DIGEST}"
