---
name: Lint

on:
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0 # needed for merge-base used in lint:links-in-modified-files

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.4.1
          sha256: c597fa1e4da76d1ea1967111d150a6a655ca51a72f4cd17fdc584be2b9eaa8bd

      - name: Lint
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: mise run lint
