---
name: Lint

on:
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0 # needed for merge-base used in lint:links-in-modified-files

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.4.7
          sha256: ba1b078f8b7988f2a800acb56105623cb72c0de8be175bfa98ad8dee16b6d603

      - name: CI checks
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: mise run ci
