services:
  otel-ebpf-profiler:
    build:
      context: ../../examples/ebpf-profiler
      dockerfile: Dockerfile
    command:
      [
        "-collection-agent",
        "lgtm:4317",
        "-no-kernel-version-check",
        "-disable-tls"
      ]
    hostname: ebpf-profiler
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /proc:/proc
    depends_on:
      - lgtm

  go:
    build:
      context: ../../examples/go
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: "rolldice"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_METRIC_EXPORT_INTERVAL: "5000" # so we don't have to wait 60s for metrics
    ports:
      - "8080:8081"
    depends_on:
      - lgtm
